sudo: false
dist: trusty
language: node_js

install:
  - uname -a

script:
  - mkdir public
  - cp -a src/. public/

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: false
  local-dir: public
  target-branch: gh-pages
  on:
    branch: stable
